[PHP]
memory_limit = 256M
upload_max_filesize = 50M
post_max_size = 50M
variables_order = "EGPCS"
max_execution_time = 60

[Date]
date.timezone = UTC

[Opcache]
opcache.enable=1
opcache.memory_consumption=256
opcache.max_accelerated_files=20000
opcache.revalidate_freq=0
opcache.validate_timestamps=1

[xdebug]
; Estas variables aplicarán solo cuando la extensión esté instalada (desarrollo)
xdebug.mode=develop,debug
xdebug.start_with_request=yes
xdebug.client_host=host.docker.internal
xdebug.client_port=9003
xdebug.log=/dev/null
